  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: store
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql01
    ports:
      - 3306:3306